language: java
jdk:
  - openjdk8

#only 밑엔 하나만 써야함.
branches:
  only:
    - dev

before_install:
  - chmod a+x gradlew

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build"

after_success:
  - ./gradlew jacocoTestReport coveralls